### ISSUE TITLE
dump_one_graph stopped working

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#188]
When using dump_graphs and dump_one_graph in fc46405790e4f0aef26be3109ade96cde78face7, this error happens:

<pre><code>SQLState: 22023
Message: SR601: Argument 0 of http_ttl_triple() should be an array of special format</code></pre>

**Comment by HughWilliams** [comment]
I have been able to recreate and reported to development to fix  (internal tracking #16184)

**Comment by HughWilliams** [comment]
The dump_graphs() function is obsolete in Virtuoso 7 with the dum_nquads() function being the more generic and reliable means of dumping the graphs in the Virtuoso Quad Store, as detailed at:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDumpNQuad

The use the normal Virtuoso Bulk load function to reload into a target Virtuoso instance if required, see:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtBulkRDFLoader

**Comment by indeyets** [comment]
@HughWilliams the only problem is, that `dump_nquads()` can not dump single named graph

**Comment by HughWilliams** [comment]
The dump_one_graph() function does still work as detailed at:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump
```
SQL> dump_one_graph ('http://localhost:8890/thalia', './data_', 1000000000);

Done. -- 2 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso VDB Server
Version 07.10.3208-pthreads for Darwin as of Mar  5 2014 
Registered to OpenLink Virtuoso (Internal Use) (Personal Edition, 50 connections)
Started on: 2014-07-31 11:08 GMT+1

$ ls -ltr data_000001.ttl*
-rw-r--r--  1 hwilliams  admin  28 31 Jul 11:13 data_000001.ttl.graph
-rw-r--r--  1 hwilliams  admin  74 31 Jul 11:13 data_000001.ttl
$
```

**Comment by urrfaust** [comment]
I can confirm the same error on my installation for dump_one_graph

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.1.1-dev.3211-pthreads as of Jul 28 2014
Compiled for Linux (x86_64-unknown-linux-gnu)

**Comment by HughWilliams** [comment]
This has been fixed with an updated procedure added to:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump

Which now gives:
```pre
SQL> dump_one_graph ('http://linked.opendata.cz/resource/dataset/seznam.gov.cz/agendy_new', './data_', 1000000000);

Done. -- 837 msec.
SQL>

[root@masala vos]# ls -ltr data_000001.ttl.*
-rw-r--r--. 1 root root     67 Sep 29 03:07 data_000001.ttl.graph
-rw-r--r--. 1 root root 637583 Sep 29 03:07 data_000001.ttl.gz
[root@masala vos]# 
```

**Comment by white-gecko** [comment]
I'm just trying to backup an old Virtuoso 6 instance that is currently running. Does anybody still have the `dump_one_graph` method to be used for Virtuoso 6?

**Comment by TallTed** [comment]
@white-gecko - Is the [`dump_one_graph` procedure source](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFDatasetDump#Procedure%20source) what you're looking for?  The previous version of this procedure can be [found here](https://github.com/openlink/virtuoso-opensource/blob/3379759437596c07e5e85b56d2450887225b9fde/docsrc/xmlsource/funcref/http_ttl_triple.xml#L64).
