### ISSUE TITLE
Sparql: xsd:boolean is occasionally returned as xsd:integer

### ISSUE THREAD

**Issue by samirjorina** [openlink/virtuoso-opensource#485]
I've got a dataset including a xsd:boolean datatype. When I query Virtuoso via Sparql, sometimes I get my data as booleans and sometimes as integers, depending on the query. Details are as below.

Virtuoso version:

```
OpenLink Virtuoso Universal Server
Version 07.20.3214-pthreads for Linux as of Oct  1 2015
```

Given the dataset as below:

```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix mp: <http://localhost/my/prefix#> .

<abb8616d-502d-4f69-9c90-b0c4d0574343>
    mp:mystring "stringvalue"^^xsd:string ;
    mp:myboolean "false"^^xsd:boolean .
```

when I execute the following Query:

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mp: <http://localhost/my/prefix#>

SELECT ?id ?mystring ?myboolean WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean ?myboolean .
    FILTER (?mystring = "stringvalue"^^xsd:string) 
}
```

I get the `myboolean` as xsd:boolean:

```
{
    'id': {
        'type': 'uri',
        'value': 'abb8616d-502d-4f69-9c90-b0c4d0574343'
    },
    'myboolean': {
        'datatype': 'http: //www.w3.org/2001/XMLSchema#boolean',
        'type': 'typed-literal',
        'value': '0'
    },
    'mystring': {
        'datatype': 'http: //www.w3.org/2001/XMLSchema#string',
        'type': 'typed-literal',
        'value': 'stringvalue'
    }
}
```

But with the following query:

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mp: <http://localhost/my/prefix#>

SELECT ?id ?mystring ?myboolean WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean ?myboolean .
    FILTER (?myboolean = "false"^^xsd:boolean) 
}
```

it is returned as xsd:integer:

```
{
    'mystring': {
        'value': 'stringvalue',
        'datatype': 'http: //www.w3.org/2001/XMLSchema#string',
        'type': 'typed-literal'
    },
    'myboolean': {
        'value': '0',
        'datatype': 'http: //www.w3.org/2001/XMLSchema#integer',
        'type': 'typed-literal'
    },
    'id': {
        'value': 'abb8616d-502d-4f69-9c90-b0c4d0574343',
        'type': 'uri'
    }
}
```

I've checked that against the source release 7.2.1 and also against code from develop/7 branch and the behavior is the same.

**Comment by IvanMikhailov** [comment]
This issue is fixed in recent fixes of the closed-source version and the patch follows a usual route to the open-source repository. The optimizer lost details and simplified

SELECT ?id ?mystring ?myboolean WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean ?myboolean .
    FILTER (?myboolean = "false"^^xsd:boolean) 
}

to

SELECT ?id ?mystring (0 as ?myboolean) WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean 0 .
}

instead of more accurate

SELECT ?id ?mystring ("false"^^xsd:boolean as ?myboolean) WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean "false"^^xsd:boolean .
}

because the SQL runtime treats "false"^^xsd:boolean and 0 as equal values.
You may still get the integer zero with queries like

PREFIX xsd: http://www.w3.org/2001/XMLSchema#
PREFIX mp: http://localhost/my/prefix#
SELECT ?id ?mystring ?myboolean WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean ?myboolean .
    FILTER (?myboolean = "false"^^xsd:boolean)
    FILTER (?myboolean = 0)
}

or

PREFIX xsd: http://www.w3.org/2001/XMLSchema#
PREFIX mp: http://localhost/my/prefix#
SELECT ?id ?mystring ?myboolean WHERE {
    ?id mp:mystring ?mystring .
    ?id mp:myboolean ?myboolean .
    FILTER (?myboolean = 0)
}

because the optimizer will put (0 as ?myboolean)

**Comment by samirjorina** [comment]
Hi,

I've retested this issue with the newest opensource release (7.2.2) and the problem still occurs. Is there any estimated date when we can expect to have it fixed? 

In your previous comment you wrote that

> This issue is fixed in recent fixes of the closed-source version and the patch follows a usual route to the open-source repository.

Are there any more details about this 'usual route'?

Thanks,
Samir
